omc = [ "1.13", "1.14", "1.15", "1.16", "1.17", "1.18", "1.19", "1.20",]
py = [ "3.6", "3.7", "3.8", "3.9", "3.10", "3.11",]
debian = [ "buster", "bullseye",]

[cache.py-images."python:3.6-stretch"]
updated-at = 2023-06-02T08:47:40.069664
exists = true

[cache.py-images."python:3.7-stretch"]
updated-at = 2023-06-02T08:47:40.072389
exists = true

[cache.py-images."python:3.8-stretch"]
updated-at = 2023-06-02T08:47:40.074802
exists = false

[cache.py-images."python:3.9-stretch"]
updated-at = 2023-06-02T08:47:40.076513
exists = false

[cache.py-images."python:3.10-stretch"]
updated-at = 2023-06-02T08:47:40.079006
exists = false

[cache.py-images."python:3.11-stretch"]
updated-at = 2023-06-02T08:47:40.081454
exists = false

[cache.py-images."python:3.6-buster"]
updated-at = 2023-06-27T01:26:38.846546
exists = true

[cache.py-images."python:3.6-bullseye"]
updated-at = 2023-06-27T01:26:38.847517
exists = true

[cache.py-images."python:3.7-buster"]
updated-at = 2023-06-27T01:26:38.848865
exists = true

[cache.py-images."python:3.7-bullseye"]
updated-at = 2023-06-27T01:26:38.850780
exists = true

[cache.py-images."python:3.8-buster"]
updated-at = 2023-06-27T01:26:38.852445
exists = true

[cache.py-images."python:3.8-bullseye"]
updated-at = 2023-06-27T01:26:38.853474
exists = true

[cache.py-images."python:3.9-buster"]
updated-at = 2023-06-27T01:26:38.864076
exists = true

[cache.py-images."python:3.9-bullseye"]
updated-at = 2023-06-27T01:26:38.867222
exists = true

[cache.py-images."python:3.10-buster"]
updated-at = 2023-06-27T01:26:38.868170
exists = true

[cache.py-images."python:3.10-bullseye"]
updated-at = 2023-06-27T01:26:38.869094
exists = true

[cache.py-images."python:3.11-buster"]
updated-at = 2023-06-27T01:26:38.870129
exists = true

[cache.py-images."python:3.11-bullseye"]
updated-at = 2023-06-27T01:26:38.872929
exists = true
