omc = [ "1.13", "1.14", "1.15", "1.16", "1.17", "1.18", "1.19", "1.20",]
py = [ "3.6", "3.7", "3.8", "3.9", "3.10", "3.11",]
debian = [ "stretch", "buster", "bullseye",]

[cache.py-images."python:3.6-stretch"]
updated-at = 2023-02-13T09:31:46.187874
exists = true

[cache.py-images."python:3.6-buster"]
updated-at = 2023-02-13T09:31:46.188754
exists = true

[cache.py-images."python:3.6-bullseye"]
updated-at = 2023-02-13T09:31:46.189293
exists = true

[cache.py-images."python:3.7-stretch"]
updated-at = 2023-02-13T09:31:46.190743
exists = true

[cache.py-images."python:3.7-buster"]
updated-at = 2023-02-13T09:31:46.191520
exists = true

[cache.py-images."python:3.7-bullseye"]
updated-at = 2023-02-13T09:31:46.192238
exists = true

[cache.py-images."python:3.8-stretch"]
updated-at = 2023-02-13T09:31:46.192880
exists = false

[cache.py-images."python:3.8-buster"]
updated-at = 2023-02-13T09:31:46.193513
exists = true

[cache.py-images."python:3.8-bullseye"]
updated-at = 2023-02-13T09:31:46.194166
exists = true

[cache.py-images."python:3.9-stretch"]
updated-at = 2023-02-13T09:31:46.195323
exists = false

[cache.py-images."python:3.9-buster"]
updated-at = 2023-02-13T09:31:46.196670
exists = true

[cache.py-images."python:3.9-bullseye"]
updated-at = 2023-02-13T09:31:46.197609
exists = true

[cache.py-images."python:3.10-stretch"]
updated-at = 2023-02-13T09:31:46.198363
exists = false

[cache.py-images."python:3.10-buster"]
updated-at = 2023-02-13T09:31:46.199611
exists = true

[cache.py-images."python:3.10-bullseye"]
updated-at = 2023-02-13T09:31:46.200364
exists = true

[cache.py-images."python:3.11-stretch"]
updated-at = 2023-02-13T09:31:46.201108
exists = false

[cache.py-images."python:3.11-buster"]
updated-at = 2023-02-13T09:31:46.202692
exists = true

[cache.py-images."python:3.11-bullseye"]
updated-at = 2023-02-13T09:31:46.238860
exists = true
