omc = [ "1.13", "1.14", "1.15", "1.16", "1.17", "1.18", "1.19", "1.20",]
py = [ "3.6", "3.7", "3.8", "3.9", "3.10", "3.11",]
debian = [ "stretch", "buster", "bullseye",]

[cache.py-images."python:3.6-stretch"]
updated-at = 2023-02-16T05:39:52.393838
exists = true

[cache.py-images."python:3.6-buster"]
updated-at = 2023-02-16T05:39:52.394701
exists = true

[cache.py-images."python:3.6-bullseye"]
updated-at = 2023-02-16T05:39:52.396358
exists = true

[cache.py-images."python:3.7-stretch"]
updated-at = 2023-02-16T05:39:52.397862
exists = true

[cache.py-images."python:3.7-buster"]
updated-at = 2023-02-16T05:39:52.400856
exists = true

[cache.py-images."python:3.7-bullseye"]
updated-at = 2023-02-16T05:39:52.411024
exists = true

[cache.py-images."python:3.8-stretch"]
updated-at = 2023-02-16T05:39:52.418848
exists = false

[cache.py-images."python:3.8-buster"]
updated-at = 2023-02-16T05:39:52.419846
exists = true

[cache.py-images."python:3.8-bullseye"]
updated-at = 2023-02-16T05:39:52.421132
exists = true

[cache.py-images."python:3.9-stretch"]
updated-at = 2023-02-16T05:39:52.421893
exists = false

[cache.py-images."python:3.9-buster"]
updated-at = 2023-02-16T05:39:52.422760
exists = true

[cache.py-images."python:3.9-bullseye"]
updated-at = 2023-02-16T05:39:52.423593
exists = true

[cache.py-images."python:3.10-stretch"]
updated-at = 2023-02-16T05:39:52.424459
exists = false

[cache.py-images."python:3.10-buster"]
updated-at = 2023-02-16T05:39:52.425790
exists = true

[cache.py-images."python:3.10-bullseye"]
updated-at = 2023-02-16T05:39:52.427298
exists = true

[cache.py-images."python:3.11-stretch"]
updated-at = 2023-02-16T05:39:52.428088
exists = false

[cache.py-images."python:3.11-buster"]
updated-at = 2023-02-16T05:39:52.430593
exists = true

[cache.py-images."python:3.11-bullseye"]
updated-at = 2023-02-16T05:39:52.436119
exists = true
