
from = [
    # v1.22
    "openmodelica/openmodelica:v1.22.3-minimal",
    "openmodelica/openmodelica:v1.22.2-minimal",
    "openmodelica/openmodelica:v1.22.1-minimal",
    "openmodelica/openmodelica:v1.22.0-minimal",
    # v1.21
    "openmodelica/openmodelica:v1.21.0-minimal",
    # v1.20
    "openmodelica/openmodelica:v1.20.0-minimal",
    # v1.19
    "openmodelica/openmodelica:v1.19.2-minimal",
    # v1.18
    "openmodelica/openmodelica:v1.18.0-minimal",
    # v1.17
    "openmodelica/openmodelica:v1.17.0-minimal",
    # v1.16
    "openmodelica/openmodelica:v1.16.2-minimal",
    "openmodelica/openmodelica:v1.16.1-minimal",
    "openmodelica/openmodelica:v1.16.0-minimal",
    # v1.15
    # v1.14
    "openmodelica/openmodelica:v1.14.2-minimal",
    "openmodelica/openmodelica:v1.14.1-minimal",
    # v1.13
    "openmodelica/openmodelica:v1.13.2-minimal",
    "openmodelica/openmodelica:v1.13.0-minimal",
]

openmodelica = []

python = [
    "3.8",
    "3.9",
    "3.10",
    "3.11",
    "3.12",
]
