omc = [ "1.13", "1.14", "1.15", "1.16", "1.17", "1.18", "1.19", "1.20", "1.21",]
py = [ "3.6", "3.7", "3.8", "3.9", "3.10", "3.11",]
debian = [ "stretch", "buster", "bullseye",]

[cache.py-images."python:3.6-stretch"]
updated-at = 2023-07-08T04:24:05.734146
exists = true

[cache.py-images."python:3.6-buster"]
updated-at = 2023-07-08T04:24:05.734779
exists = true

[cache.py-images."python:3.6-bullseye"]
updated-at = 2023-07-08T04:24:05.735400
exists = true

[cache.py-images."python:3.7-stretch"]
updated-at = 2023-07-08T04:24:05.736097
exists = true

[cache.py-images."python:3.7-buster"]
updated-at = 2023-07-08T04:24:05.737153
exists = true

[cache.py-images."python:3.7-bullseye"]
updated-at = 2023-07-08T04:24:05.738252
exists = true

[cache.py-images."python:3.8-stretch"]
updated-at = 2023-07-08T04:24:05.741535
exists = false

[cache.py-images."python:3.8-buster"]
updated-at = 2023-07-08T04:24:05.742890
exists = true

[cache.py-images."python:3.8-bullseye"]
updated-at = 2023-07-08T04:24:05.744003
exists = true

[cache.py-images."python:3.9-stretch"]
updated-at = 2023-07-08T04:24:05.744891
exists = false

[cache.py-images."python:3.9-buster"]
updated-at = 2023-07-08T04:24:05.754965
exists = true

[cache.py-images."python:3.9-bullseye"]
updated-at = 2023-07-08T04:24:05.759085
exists = true

[cache.py-images."python:3.10-stretch"]
updated-at = 2023-07-08T04:24:05.760358
exists = false

[cache.py-images."python:3.10-buster"]
updated-at = 2023-07-08T04:24:05.763346
exists = true

[cache.py-images."python:3.10-bullseye"]
updated-at = 2023-07-08T04:24:05.765158
exists = true

[cache.py-images."python:3.11-stretch"]
updated-at = 2023-07-08T04:24:05.766595
exists = false

[cache.py-images."python:3.11-buster"]
updated-at = 2023-07-08T04:24:05.769932
exists = true

[cache.py-images."python:3.11-bullseye"]
updated-at = 2023-07-08T04:24:05.771571
exists = true
