omc = [ "1.13", "1.14", "1.15", "1.16", "1.17", "1.18", "1.19", "1.20", "1.21",]
py = [ "3.6", "3.7", "3.8", "3.9", "3.10", "3.11",]
debian = [ "buster", "bullseye",]

[cache.py-images."python:3.6-stretch"]
updated-at = 2023-06-02T08:47:40.069664
exists = true

[cache.py-images."python:3.7-stretch"]
updated-at = 2023-06-02T08:47:40.072389
exists = true

[cache.py-images."python:3.8-stretch"]
updated-at = 2023-06-02T08:47:40.074802
exists = false

[cache.py-images."python:3.9-stretch"]
updated-at = 2023-06-02T08:47:40.076513
exists = false

[cache.py-images."python:3.10-stretch"]
updated-at = 2023-06-02T08:47:40.079006
exists = false

[cache.py-images."python:3.11-stretch"]
updated-at = 2023-06-02T08:47:40.081454
exists = false

[cache.py-images."python:3.6-buster"]
updated-at = 2023-06-29T05:35:11.338127
exists = true

[cache.py-images."python:3.6-bullseye"]
updated-at = 2023-06-29T05:35:11.339308
exists = true

[cache.py-images."python:3.7-buster"]
updated-at = 2023-06-29T05:35:11.340449
exists = true

[cache.py-images."python:3.7-bullseye"]
updated-at = 2023-06-29T05:35:11.341256
exists = true

[cache.py-images."python:3.8-buster"]
updated-at = 2023-06-29T05:35:11.342113
exists = true

[cache.py-images."python:3.8-bullseye"]
updated-at = 2023-06-29T05:35:11.342989
exists = true

[cache.py-images."python:3.9-buster"]
updated-at = 2023-06-29T05:35:11.346883
exists = true

[cache.py-images."python:3.9-bullseye"]
updated-at = 2023-06-29T05:35:11.348204
exists = true

[cache.py-images."python:3.10-buster"]
updated-at = 2023-06-29T05:35:11.348806
exists = true

[cache.py-images."python:3.10-bullseye"]
updated-at = 2023-06-29T05:35:11.349336
exists = true

[cache.py-images."python:3.11-buster"]
updated-at = 2023-06-29T05:35:11.349855
exists = true

[cache.py-images."python:3.11-bullseye"]
updated-at = 2023-06-29T05:35:11.350314
exists = true
