
from = [
    "openmodelica/openmodelica:v1.22.0-minimal",
    "openmodelica/openmodelica:v1.21.0-minimal",
    "openmodelica/openmodelica:v1.20.0-minimal",
    "openmodelica/openmodelica:v1.19.2-minimal",
    "openmodelica/openmodelica:v1.18.0-minimal",
    # "openmodelica/openmodelica:v1.17.0-minimal",
    # "openmodelica/openmodelica:v1.16.2-minimal",
    # "openmodelica/openmodelica:v1.16.1-minimal",
    # "openmodelica/openmodelica:v1.16.0-minimal",
    # "openmodelica/openmodelica:v1.14.2-minimal",
    # "openmodelica/openmodelica:v1.14.1-minimal",
    # "openmodelica/openmodelica:v1.13.2-minimal",
    # "openmodelica/openmodelica:v1.13.0-minimal",
]

python = [
    # "3.6",
    # "3.7",
    # "3.8",
    # "3.9",
    "3.10",
    # "3.11",
    # "3.12",
]
# debian = [ "stretch", "buster", "bullseye", "bookworm",]

# [cache.py-images."python:3.6-bookworm"]
# updated-at = 2023-11-21T03:18:56.442355
# exists = false

# [cache.py-images."python:3.7-buster"]
# updated-at = 2023-11-21T03:18:56.445456
# exists = true

# [cache.py-images."python:3.8-stretch"]
# updated-at = 2023-11-21T03:18:56.448698
# exists = false

# [cache.py-images."python:3.8-buster"]
# updated-at = 2023-11-21T03:18:56.450100
# exists = true

# [cache.py-images."python:3.9-stretch"]
# updated-at = 2023-11-21T03:18:56.453205
# exists = false

# [cache.py-images."python:3.9-buster"]
# updated-at = 2023-11-21T03:18:56.467523
# exists = true

# [cache.py-images."python:3.10-stretch"]
# updated-at = 2023-11-21T03:18:56.472026
# exists = false

# [cache.py-images."python:3.11-stretch"]
# updated-at = 2023-11-21T03:18:56.484515
# exists = false

# [cache.py-images."python:3.11-buster"]
# updated-at = 2023-11-21T03:18:56.486380
# exists = true

# [cache.py-images."python:3.12-stretch"]
# updated-at = 2023-11-21T03:18:56.496815
# exists = false

# [cache.py-images."python:3.12-buster"]
# updated-at = 2023-11-21T03:18:56.501021
# exists = false

# [cache.py-images."python:3.10-buster"]
# updated-at = 2023-11-21T08:33:53.422368
# exists = true

# [cache.py-images."python:3.6-stretch"]
# updated-at = 2023-11-21T12:44:37.960693
# exists = true

# [cache.py-images."python:3.6-buster"]
# updated-at = 2023-11-21T12:44:37.966507
# exists = true

# [cache.py-images."python:3.6-bullseye"]
# updated-at = 2023-11-21T12:44:37.969066
# exists = true

# [cache.py-images."python:3.7-stretch"]
# updated-at = 2023-11-21T12:44:37.970410
# exists = true

# [cache.py-images."python:3.7-bullseye"]
# updated-at = 2023-11-21T12:44:37.971136
# exists = true

# [cache.py-images."python:3.7-bookworm"]
# updated-at = 2023-11-21T12:44:37.971755
# exists = true

# [cache.py-images."python:3.8-bullseye"]
# updated-at = 2023-11-21T12:44:37.972439
# exists = true

# [cache.py-images."python:3.8-bookworm"]
# updated-at = 2023-11-21T12:44:37.973227
# exists = true

# [cache.py-images."python:3.9-bullseye"]
# updated-at = 2023-11-21T12:44:37.974968
# exists = true

# [cache.py-images."python:3.9-bookworm"]
# updated-at = 2023-11-21T12:44:37.977215
# exists = true

# [cache.py-images."python:3.10-bullseye"]
# updated-at = 2023-11-21T12:44:37.979646
# exists = true

# [cache.py-images."python:3.10-bookworm"]
# updated-at = 2023-11-21T12:44:37.983055
# exists = true

# [cache.py-images."python:3.11-bullseye"]
# updated-at = 2023-11-21T12:44:37.985829
# exists = true

# [cache.py-images."python:3.11-bookworm"]
# updated-at = 2023-11-21T12:44:37.987512
# exists = true

# [cache.py-images."python:3.12-bullseye"]
# updated-at = 2023-11-21T12:44:37.989255
# exists = true

# [cache.py-images."python:3.12-bookworm"]
# updated-at = 2023-11-21T12:44:37.990572
# exists = true
