omc = [ "1.13", "1.14", "1.15", "1.16", "1.17", "1.18", "1.19", "1.20", "1.21",]
py = [ "3.6", "3.7", "3.8", "3.9", "3.10", "3.11",]
debian = [ "stretch", "buster", "bullseye",]

[cache.py-images."python:3.6-stretch"]
updated-at = 2023-07-19T00:55:25.874323
exists = true

[cache.py-images."python:3.6-buster"]
updated-at = 2023-07-19T00:55:25.875580
exists = true

[cache.py-images."python:3.6-bullseye"]
updated-at = 2023-07-19T00:55:25.876286
exists = true

[cache.py-images."python:3.7-stretch"]
updated-at = 2023-07-19T00:55:25.878123
exists = true

[cache.py-images."python:3.7-buster"]
updated-at = 2023-07-19T00:55:25.879152
exists = true

[cache.py-images."python:3.7-bullseye"]
updated-at = 2023-07-19T00:55:25.880308
exists = true

[cache.py-images."python:3.8-stretch"]
updated-at = 2023-07-19T00:55:25.881835
exists = false

[cache.py-images."python:3.8-buster"]
updated-at = 2023-07-19T00:55:25.882582
exists = true

[cache.py-images."python:3.8-bullseye"]
updated-at = 2023-07-19T00:55:25.883360
exists = true

[cache.py-images."python:3.9-stretch"]
updated-at = 2023-07-19T00:55:25.884439
exists = false

[cache.py-images."python:3.9-buster"]
updated-at = 2023-07-19T00:55:25.885959
exists = true

[cache.py-images."python:3.9-bullseye"]
updated-at = 2023-07-19T00:55:25.886776
exists = true

[cache.py-images."python:3.10-stretch"]
updated-at = 2023-07-19T00:55:25.887516
exists = false

[cache.py-images."python:3.10-buster"]
updated-at = 2023-07-19T00:55:25.889775
exists = true

[cache.py-images."python:3.10-bullseye"]
updated-at = 2023-07-19T00:55:25.890574
exists = true

[cache.py-images."python:3.11-stretch"]
updated-at = 2023-07-19T00:55:25.891914
exists = false

[cache.py-images."python:3.11-buster"]
updated-at = 2023-07-19T00:55:25.896736
exists = true

[cache.py-images."python:3.11-bullseye"]
updated-at = 2023-07-19T00:55:25.903712
exists = true
