omc = [ "1.13", "1.14", "1.15", "1.16", "1.17", "1.18", "1.19", "1.20", "1.21",]
py = [ "3.6", "3.7", "3.8", "3.9", "3.10", "3.11",]
debian = [ "stretch", "buster", "bullseye",]

[cache.py-images."python:3.6-stretch"]
updated-at = 2023-10-20T04:39:16.762923
exists = true

[cache.py-images."python:3.7-stretch"]
updated-at = 2023-10-20T04:39:16.767095
exists = true

[cache.py-images."python:3.7-buster"]
updated-at = 2023-10-20T04:39:16.767955
exists = true

[cache.py-images."python:3.8-stretch"]
updated-at = 2023-10-20T04:39:16.769252
exists = false

[cache.py-images."python:3.8-buster"]
updated-at = 2023-10-20T04:39:16.769913
exists = true

[cache.py-images."python:3.9-stretch"]
updated-at = 2023-10-20T04:39:16.771136
exists = false

[cache.py-images."python:3.9-buster"]
updated-at = 2023-10-20T04:39:16.772336
exists = true

[cache.py-images."python:3.10-stretch"]
updated-at = 2023-10-20T04:39:16.773774
exists = false

[cache.py-images."python:3.10-buster"]
updated-at = 2023-10-20T04:39:16.774462
exists = true

[cache.py-images."python:3.11-stretch"]
updated-at = 2023-10-20T04:39:16.775986
exists = false

[cache.py-images."python:3.11-buster"]
updated-at = 2023-10-20T04:39:16.776850
exists = true

[cache.py-images."python:3.6-buster"]
updated-at = 2023-10-20T04:39:58.328183
exists = true

[cache.py-images."python:3.6-bullseye"]
updated-at = 2023-10-20T04:39:58.329812
exists = true

[cache.py-images."python:3.7-bullseye"]
updated-at = 2023-10-20T04:39:58.330565
exists = true

[cache.py-images."python:3.8-bullseye"]
updated-at = 2023-10-20T04:39:58.331743
exists = true

[cache.py-images."python:3.9-bullseye"]
updated-at = 2023-10-20T04:39:58.332648
exists = true

[cache.py-images."python:3.10-bullseye"]
updated-at = 2023-10-20T04:39:58.333305
exists = true

[cache.py-images."python:3.11-bullseye"]
updated-at = 2023-10-20T04:39:58.334299
exists = true
