omc = [ "1.13", "1.14", "1.15", "1.16", "1.17", "1.18", "1.19", "1.20",]
py = [ "3.6", "3.7", "3.8", "3.9", "3.10", "3.11",]
debian = [ "stretch", "buster", "bullseye",]

[cache.py-images."python:3.6-stretch"]
updated-at = 2023-06-02T08:47:40.069664
exists = true

[cache.py-images."python:3.6-buster"]
updated-at = 2023-06-02T08:47:40.070757
exists = true

[cache.py-images."python:3.6-bullseye"]
updated-at = 2023-06-02T08:47:40.071586
exists = true

[cache.py-images."python:3.7-stretch"]
updated-at = 2023-06-02T08:47:40.072389
exists = true

[cache.py-images."python:3.7-buster"]
updated-at = 2023-06-02T08:47:40.073249
exists = true

[cache.py-images."python:3.7-bullseye"]
updated-at = 2023-06-02T08:47:40.074183
exists = true

[cache.py-images."python:3.8-stretch"]
updated-at = 2023-06-02T08:47:40.074802
exists = false

[cache.py-images."python:3.8-buster"]
updated-at = 2023-06-02T08:47:40.075354
exists = true

[cache.py-images."python:3.8-bullseye"]
updated-at = 2023-06-02T08:47:40.076036
exists = true

[cache.py-images."python:3.9-stretch"]
updated-at = 2023-06-02T08:47:40.076513
exists = false

[cache.py-images."python:3.9-buster"]
updated-at = 2023-06-02T08:47:40.076973
exists = true

[cache.py-images."python:3.9-bullseye"]
updated-at = 2023-06-02T08:47:40.077709
exists = true

[cache.py-images."python:3.10-stretch"]
updated-at = 2023-06-02T08:47:40.079006
exists = false

[cache.py-images."python:3.10-buster"]
updated-at = 2023-06-02T08:47:40.079760
exists = true

[cache.py-images."python:3.10-bullseye"]
updated-at = 2023-06-02T08:47:40.080412
exists = true

[cache.py-images."python:3.11-stretch"]
updated-at = 2023-06-02T08:47:40.081454
exists = false

[cache.py-images."python:3.11-buster"]
updated-at = 2023-06-02T08:47:40.082392
exists = true

[cache.py-images."python:3.11-bullseye"]
updated-at = 2023-06-02T08:47:40.082977
exists = true
