omc = [ "1.13", "1.14", "1.15", "1.16", "1.17", "1.18", "1.19", "1.20", "1.21", "1.22",]
py = [ "3.6", "3.7", "3.8", "3.9", "3.10", "3.11", "3.12",]
debian = [ "stretch", "buster", "bullseye", "bookworm",]

[cache.py-images."python:3.6-stretch"]
updated-at = 2023-11-14T02:39:10.560064
exists = true

[cache.py-images."python:3.6-buster"]
updated-at = 2023-11-14T02:39:10.561273
exists = true

[cache.py-images."python:3.6-bullseye"]
updated-at = 2023-11-14T02:39:10.562508
exists = true

[cache.py-images."python:3.6-bookworm"]
updated-at = 2023-11-14T02:39:10.564371
exists = false

[cache.py-images."python:3.7-stretch"]
updated-at = 2023-11-14T02:39:10.567562
exists = true

[cache.py-images."python:3.7-buster"]
updated-at = 2023-11-14T02:39:10.570124
exists = true

[cache.py-images."python:3.7-bullseye"]
updated-at = 2023-11-14T02:39:10.570982
exists = true

[cache.py-images."python:3.7-bookworm"]
updated-at = 2023-11-14T02:39:10.574118
exists = true

[cache.py-images."python:3.8-stretch"]
updated-at = 2023-11-14T02:39:10.575292
exists = false

[cache.py-images."python:3.8-buster"]
updated-at = 2023-11-14T02:39:10.576123
exists = true

[cache.py-images."python:3.8-bullseye"]
updated-at = 2023-11-14T02:39:10.578487
exists = true

[cache.py-images."python:3.8-bookworm"]
updated-at = 2023-11-14T02:39:10.579275
exists = true

[cache.py-images."python:3.9-stretch"]
updated-at = 2023-11-14T02:39:10.580056
exists = false

[cache.py-images."python:3.9-buster"]
updated-at = 2023-11-14T02:39:10.581083
exists = true

[cache.py-images."python:3.9-bullseye"]
updated-at = 2023-11-14T02:39:10.583949
exists = true

[cache.py-images."python:3.9-bookworm"]
updated-at = 2023-11-14T02:39:10.585658
exists = true

[cache.py-images."python:3.10-stretch"]
updated-at = 2023-11-14T02:39:10.586366
exists = false

[cache.py-images."python:3.10-buster"]
updated-at = 2023-11-14T02:39:10.587315
exists = true

[cache.py-images."python:3.10-bullseye"]
updated-at = 2023-11-14T02:39:10.587965
exists = true

[cache.py-images."python:3.10-bookworm"]
updated-at = 2023-11-14T02:39:10.588718
exists = true

[cache.py-images."python:3.11-stretch"]
updated-at = 2023-11-14T02:39:10.589989
exists = false

[cache.py-images."python:3.11-buster"]
updated-at = 2023-11-14T02:39:10.593342
exists = true

[cache.py-images."python:3.11-bullseye"]
updated-at = 2023-11-14T02:39:10.594154
exists = true

[cache.py-images."python:3.11-bookworm"]
updated-at = 2023-11-14T02:39:10.596467
exists = true

[cache.py-images."python:3.12-stretch"]
updated-at = 2023-11-15T04:01:42.079514
exists = false

[cache.py-images."python:3.12-buster"]
updated-at = 2023-11-15T04:01:42.081223
exists = false

[cache.py-images."python:3.12-bullseye"]
updated-at = 2023-11-15T04:01:42.082658
exists = true

[cache.py-images."python:3.12-bookworm"]
updated-at = 2023-11-15T04:01:42.085293
exists = true
