omc = [ "1.13", "1.14", "1.15", "1.16", "1.17", "1.18", "1.19", "1.20",]
py = [ "3.6", "3.7", "3.8", "3.9", "3.10", "3.11",]
debian = [ "stretch", "buster", "bullseye",]

[cache.py-images."python:3.11-bullseye"]
updated-at = 2023-02-07T09:41:48.656487
exists = true

[cache.py-images."python:3.7-stretch"]
updated-at = 2023-02-07T09:41:48.644578
exists = true

[cache.py-images."python:3.7-buster"]
updated-at = 2023-02-07T09:41:48.645693
exists = true

[cache.py-images."python:3.7-bullseye"]
updated-at = 2023-02-07T09:40:51.246008
exists = true

[cache.py-images."python:3.11-stretch"]
updated-at = 2023-02-07T09:41:48.653911
exists = false

[cache.py-images."python:3.11-buster"]
updated-at = 2023-02-07T09:41:48.654522
exists = true

[cache.py-images."python:3.8-stretch"]
updated-at = 2023-02-07T09:41:48.647343
exists = false

[cache.py-images."python:3.8-buster"]
updated-at = 2023-02-07T09:41:48.648141
exists = true

[cache.py-images."python:3.8-bullseye"]
updated-at = 2023-02-07T09:40:51.247916
exists = true

[cache.py-images."python:3.9-stretch"]
updated-at = 2023-02-07T09:41:48.649617
exists = false

[cache.py-images."python:3.9-buster"]
updated-at = 2023-02-07T09:41:48.650231
exists = true

[cache.py-images."python:3.9-bullseye"]
updated-at = 2023-02-07T09:40:51.251260
exists = true

[cache.py-images."python:3.10-stretch"]
updated-at = 2023-02-07T09:41:48.652052
exists = false

[cache.py-images."python:3.10-buster"]
updated-at = 2023-02-07T09:41:48.652565
exists = true

[cache.py-images."python:3.10-bullseye"]
updated-at = 2023-02-07T09:40:51.253055
exists = true

[cache.py-images."python:3.6-stretch"]
updated-at = 2023-02-07T12:09:10.557924
exists = true

[cache.py-images."python:3.6-bullseye"]
updated-at = 2023-02-07T12:09:10.560250
exists = true

[cache.py-images."python:3.6-buster"]
updated-at = 2023-02-07T12:09:10.558982
exists = true
