omc = [
    "1.13",
    "1.14",
    "1.15",
    "1.16",
    "1.17",
    "1.18",
    "1.19",
    "1.20",
]

py = [
    "3.7",
    "3.8",
    "3.9",
    "3.10",
    "3.11",
]

debian = [
    "stretch",
    "buster",
    "bullseye",
]

[cache.py-images."python:3.11-bullseye"]
updated-at = 2023-02-06T17:03:26.605213
exists = true

[cache.py-images."python:3.7-stretch"]
updated-at = 2023-02-06T17:04:06.684011
exists = true

[cache.py-images."python:3.7-buster"]
updated-at = 2023-02-06T17:04:13.614089
exists = true

[cache.py-images."python:3.7-bullseye"]
updated-at = 2023-02-06T17:04:19.267021
exists = true

[cache.py-images."python:3.11-stretch"]
updated-at = 2023-02-06T17:04:25.295933
exists = false

[cache.py-images."python:3.11-buster"]
updated-at = 2023-02-06T17:04:32.847953
exists = true

[cache.py-images."python:3.8-stretch"]
updated-at = 2023-02-06T17:06:50.552341
exists = false

[cache.py-images."python:3.8-buster"]
updated-at = 2023-02-06T17:06:56.532923
exists = true

[cache.py-images."python:3.8-bullseye"]
updated-at = 2023-02-06T17:07:02.640547
exists = true

[cache.py-images."python:3.9-stretch"]
updated-at = 2023-02-06T17:07:08.276957
exists = false

[cache.py-images."python:3.9-buster"]
updated-at = 2023-02-06T17:07:13.992903
exists = true

[cache.py-images."python:3.9-bullseye"]
updated-at = 2023-02-06T17:07:23.995333
exists = true

[cache.py-images."python:3.10-stretch"]
updated-at = 2023-02-06T17:07:36.358397
exists = false

[cache.py-images."python:3.10-buster"]
updated-at = 2023-02-06T17:07:42.130603
exists = true

[cache.py-images."python:3.10-bullseye"]
updated-at = 2023-02-06T17:07:47.879607
exists = true
