omc = [ "1.13", "1.14", "1.15", "1.16", "1.17", "1.18", "1.19", "1.20", "1.21", "1.22",]
py = [ "3.6", "3.7", "3.8", "3.9", "3.10", "3.11", "3.12",]
debian = [ "stretch", "buster", "bullseye", "bookworm",]

[cache.py-images."python:3.12-bullseye"]
updated-at = 2023-11-15T04:01:42.082658
exists = true

[cache.py-images."python:3.12-bookworm"]
updated-at = 2023-11-15T04:01:42.085293
exists = true

[cache.py-images."python:3.6-stretch"]
updated-at = 2023-11-17T00:36:58.389436
exists = true

[cache.py-images."python:3.6-buster"]
updated-at = 2023-11-17T00:36:58.390814
exists = true

[cache.py-images."python:3.6-bullseye"]
updated-at = 2023-11-17T00:36:58.391823
exists = true

[cache.py-images."python:3.7-stretch"]
updated-at = 2023-11-17T00:36:58.394330
exists = true

[cache.py-images."python:3.7-bullseye"]
updated-at = 2023-11-17T00:36:58.396060
exists = true

[cache.py-images."python:3.7-bookworm"]
updated-at = 2023-11-17T00:36:58.396953
exists = true

[cache.py-images."python:3.8-bullseye"]
updated-at = 2023-11-17T00:36:58.399687
exists = true

[cache.py-images."python:3.8-bookworm"]
updated-at = 2023-11-17T00:36:58.400374
exists = true

[cache.py-images."python:3.9-bullseye"]
updated-at = 2023-11-17T00:36:58.405293
exists = true

[cache.py-images."python:3.9-bookworm"]
updated-at = 2023-11-17T00:36:58.407743
exists = true

[cache.py-images."python:3.10-buster"]
updated-at = 2023-11-17T00:36:58.409724
exists = true

[cache.py-images."python:3.10-bullseye"]
updated-at = 2023-11-17T00:36:58.410522
exists = true

[cache.py-images."python:3.10-bookworm"]
updated-at = 2023-11-17T00:36:58.411364
exists = true

[cache.py-images."python:3.11-bullseye"]
updated-at = 2023-11-17T00:36:58.419221
exists = true

[cache.py-images."python:3.11-bookworm"]
updated-at = 2023-11-17T00:36:58.420741
exists = true

[cache.py-images."python:3.6-bookworm"]
updated-at = 2023-11-21T03:18:56.442355
exists = false

[cache.py-images."python:3.7-buster"]
updated-at = 2023-11-21T03:18:56.445456
exists = true

[cache.py-images."python:3.8-stretch"]
updated-at = 2023-11-21T03:18:56.448698
exists = false

[cache.py-images."python:3.8-buster"]
updated-at = 2023-11-21T03:18:56.450100
exists = true

[cache.py-images."python:3.9-stretch"]
updated-at = 2023-11-21T03:18:56.453205
exists = false

[cache.py-images."python:3.9-buster"]
updated-at = 2023-11-21T03:18:56.467523
exists = true

[cache.py-images."python:3.10-stretch"]
updated-at = 2023-11-21T03:18:56.472026
exists = false

[cache.py-images."python:3.11-stretch"]
updated-at = 2023-11-21T03:18:56.484515
exists = false

[cache.py-images."python:3.11-buster"]
updated-at = 2023-11-21T03:18:56.486380
exists = true

[cache.py-images."python:3.12-stretch"]
updated-at = 2023-11-21T03:18:56.496815
exists = false

[cache.py-images."python:3.12-buster"]
updated-at = 2023-11-21T03:18:56.501021
exists = false
