omc = [ "1.13", "1.14", "1.15", "1.16", "1.17", "1.18", "1.19", "1.20",]
py = [ "3.6", "3.7", "3.8", "3.9", "3.10", "3.11",]
debian = [ "stretch", "buster", "bullseye",]

[cache.py-images."python:3.6-stretch"]
updated-at = 2023-02-22T04:46:31.541409
exists = true

[cache.py-images."python:3.6-buster"]
updated-at = 2023-02-22T04:46:31.543070
exists = true

[cache.py-images."python:3.6-bullseye"]
updated-at = 2023-02-22T04:46:31.544208
exists = true

[cache.py-images."python:3.7-stretch"]
updated-at = 2023-02-22T04:46:31.545026
exists = true

[cache.py-images."python:3.7-buster"]
updated-at = 2023-02-22T04:46:31.546377
exists = true

[cache.py-images."python:3.7-bullseye"]
updated-at = 2023-02-22T04:46:31.547063
exists = true

[cache.py-images."python:3.8-stretch"]
updated-at = 2023-02-22T04:46:31.547647
exists = false

[cache.py-images."python:3.8-buster"]
updated-at = 2023-02-22T04:46:31.548322
exists = true

[cache.py-images."python:3.8-bullseye"]
updated-at = 2023-02-22T04:46:31.549529
exists = true

[cache.py-images."python:3.9-stretch"]
updated-at = 2023-02-22T04:46:31.550093
exists = false

[cache.py-images."python:3.9-buster"]
updated-at = 2023-02-22T04:46:31.550834
exists = true

[cache.py-images."python:3.9-bullseye"]
updated-at = 2023-02-22T04:46:31.551489
exists = true

[cache.py-images."python:3.10-stretch"]
updated-at = 2023-02-22T04:46:31.552103
exists = false

[cache.py-images."python:3.10-buster"]
updated-at = 2023-02-22T04:46:31.552781
exists = true

[cache.py-images."python:3.10-bullseye"]
updated-at = 2023-02-22T04:46:31.553428
exists = true

[cache.py-images."python:3.11-stretch"]
updated-at = 2023-02-22T04:46:31.554984
exists = false

[cache.py-images."python:3.11-buster"]
updated-at = 2023-02-22T04:46:31.555635
exists = true

[cache.py-images."python:3.11-bullseye"]
updated-at = 2023-02-22T04:46:31.557049
exists = true
